version: '3'
services:
  misp:
    image: tobmes42/misp-docker:core-latest
    build:
        context: server/.
        args:
            - MISP_TAG=${MISP_TAG}
            - PHP_VER=${PHP_VER}

  misp-modules:
    image: tobmes42/misp-docker:modules-latest
    build:
        context: modules/.
        args:
            - MODULES_TAG=${MODULES_TAG}
